<?php defined('ABSPATH') or die('Cheatin\' uh?');
/**
 * 
**/
CSF::createSection(MTHAN_THEME_OPTIONS, [
    'id' => 'typography_settings',
    'title' => 'Typography',
    'icon' => 'fas fa-font',
    'fields' => [
        [
            'id'               => 'body_typography',
            'type'             => 'typography',
            'title'            => 'Body Typography',
            'output'           => 'body',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Inter',
                'font-weight'     => '400',
                'font-size'       => '16px',
                'line-height'     => '1.6',
                'color'           => '#666666',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'h1_typography',
            'type'             => 'typography',
            'title'            => 'Heading H1',
            'output'           => 'h1',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Libre Baskerville',
                'font-weight'     => '700',
                'font-size'       => '48px',
                'line-height'     => '1.2',
                'color'           => '#222222',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'h2_typography',
            'type'             => 'typography',
            'title'            => 'Heading H2',
            'output'           => 'h2',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Libre Baskerville',
                'font-weight'     => '700',
                'font-size'       => '36px',
                'line-height'     => '1.3',
                'color'           => '#222222',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'h3_typography',
            'type'             => 'typography',
            'title'            => 'Heading H3',
            'output'           => 'h3',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Libre Baskerville',
                'font-weight'     => '700',
                'font-size'       => '28px',
                'line-height'     => '1.3',
                'color'           => '#222222',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'h4_typography',
            'type'             => 'typography',
            'title'            => 'Heading H4',
            'output'           => 'h4',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Libre Baskerville',
                'font-weight'     => '700',
                'font-size'       => '22px',
                'line-height'     => '1.4',
                'color'           => '#222222',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'h5_typography',
            'type'             => 'typography',
            'title'            => 'Heading H5',
            'output'           => 'h5',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Libre Baskerville',
                'font-weight'     => '700',
                'font-size'       => '18px',
                'line-height'     => '1.4',
                'color'           => '#222222',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'h6_typography',
            'type'             => 'typography',
            'title'            => 'Heading H6',
            'output'           => 'h6',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Libre Baskerville',
                'font-weight'     => '700',
                'font-size'       => '16px',
                'line-height'     => '1.5',
                'color'           => '#222222',
                'type'            => 'google',
            ],
        ],
        [
            'id'               => 'accent_typography',
            'type'             => 'typography',
            'title'            => 'Accent / Button Typography',
            'output'           => '.theme-btn, .accent-font',
            'output_variables' => true,
            'default'          => [
                'font-family'     => 'Inter',
                'font-weight'     => '600',
                'type'            => 'google',
            ],
        ],
    ]
]);
